events:
  - virtual: false
    show: true
    location: "Cape Town"
    menuTitle: "Cape Town"
    date: "5 April 2022"
    info: "/capetown"
    infoOn: true
    sessionizeId: "p87oviq3"
    logo: devconfcpt.png
    minattendees: 250
    venue: "Lagoon Beach Hotel & Spa"
    website: "https://www.lagoonbeachhotel.co.za/"
    mapLink: "https://g.page/LagoonBeachHotelSpa?share"
    lat: "-33.89207"
    long: "18.48262"
    sponsorOpen: true
    colour: blue
    tickets:
      onsale: false
      purchaseSite: "https://www.quicket.co.za/events/150961-devconf-2022-cape-town"
      fullprice:
        price: "R3,142"
        sold_out: true
      earlybird:
        price: "R2,825" 
        sold_out: true  
    rooms: 
      room_1: "Atlantic 2"
      room_2: "Atlantic 1"
      room_3: "Marine"
      room_4: "Courtyard 1"
      room_5: "Courtyard 2"
  - virtual: true
    show: true
    menuTitle: "Virtual"
    location: "Virtual"
    date: "7 April 2022"
    info: "/virtual"
    infoOn: true
    sessionizeId: "p87oviq3"
    logo: devconfvirtual.png
    minattendees: 250
    sponsorOpen: true
    colour: third
    tickets:
      onsale: true
      purchaseSite: "https://www.quicket.co.za/events/150965-devconf-2022-virtual"
      fullprice:
        price: "R3,142"
      earlybird:
        price: "R2,825"  
        sold_out: false  
    rooms: 
      room_1: "Stream 1"
      room_2: "Stream 2"
      room_3: "Stream 3"
      room_4: "Stream 4"
      room_5: "Stream 5"   
  - virtual: false
    show: true
    location: "Johannesburg"
    menuTitle: "Joburg"
    date: "7 April 2022"
    info: "/joburg"
    infoOn: true
    sessionizeId: "p87oviq3"
    logo: devconfjhb.png
    minattendees: 250
    venue: "The Canvas | Riversands Conferencing"
    website: "https://www.thecanvasriversands.co.za/"
    mapLink: "https://g.page/TheCanvasRiversandsConference?share"
    lat: "-25.96448"
    long: "28.019760"
    sponsorOpen: true
    colour: pink
    tickets:
      onsale: false
      purchaseSite: "https://www.quicket.co.za/events/150895-devconf-2022-johannesburg"
      fullprice:
        price: "R3,142"
        sold_out: true
      earlybird:
        price: "R2,825"  
        sold_out: true     
    rooms: 
      room_1: "Auditorium"
      room_2: "Training Room 3"
      room_3: "Training Room 10"
      room_4: "Hall 1"
      room_5: "Hall 2"