sponsors:
    proposal: /public/docs/DevConf 2024 Sponsorship Proposal.pdf
callForSpeakers:
    show: false
    link: https://sessionize.com/devconf-2024
events:
    - virtual: false
      show: true
      showAgenda: true
      location: "Johannesburg"
      menuTitle: "Joburg"
      date: "7 May 2024"
      info: "/joburg"
      infoOn: true
      sessionizeId: "b0tah92u"
      logo: devconfjhb.png
      minattendees: 700
      venue: "Emperors Palace Conference Centre"
      website: "https://emperorspalace.com/conferences-overview/"
      mapLink: "https://goo.gl/maps/eQKGw5XmjA5RjPQa8"
      lat: "-26.146498178859964"
      long: "28.223241542328243"
      sponsorOpen: true
      colour: pink
      tickets:
          totally_sold_out: false
          onsale: true
          has_shuttle: false
          has_waiting_list: false
          waiting_list:
          purchaseSite: "https://www.quicket.co.za/events/237752-devconf-2024-johannesburg"
          merch_link: ""
          fullprice:
              price: 3623
              bulkPrice: 3293.64
              sold_out: false
          earlybird:
              price: 3150.43
              sold_out: true
      rooms:
          room_1: "Centre Court"
          room_2: "NCC"
          room_3: "Senate I"
          room_4: "Senate II"
          room_5: "Fabia"
      workshops:
          workshop1:
              enabled: true
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              room: Julia
          workshop2:
              enabled: true
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              room: Julia
          workshop3:
              enabled: true
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              room: Julia
    - virtual: false
      show: true
      showAgenda: true
      location: "Cape Town"
      menuTitle: "Cape Town"
      date: "9 May 2024"
      info: "/capetown"
      infoOn: true
      sessionizeId: "b0tah92u"
      logo: devconfcpt.png
      minattendees: 700
      venue: "Century City Conference Centre"
      website: "http://ccconferencecentre.co.za/"
      mapLink: "https://goo.gl/maps/T8F9LTbNdFHZTEzw9"
      lat: "-33.895519679277136"
      long: "18.504693653133835"
      sponsorOpen: true
      colour: blue
      tickets:
          onsale: true
          totally_sold_out: false
          has_shuttle: false
          has_waiting_list: false
          waiting_list: ""
          purchaseSite: "https://www.quicket.co.za/events/239304-devconf-2024-cape-town"
          merch_link:
          fullprice:
              price: 3623
              sold_out: false
              bulkPrice: 3293.64
          earlybird:
              price: 3150.43
              sold_out: true
      rooms:
          room_1: "Hall A"
          room_2: "Hall B"
          room_3: "Hall C"
          room_4: "Meeting Room 11"
          room_5: "Meeting Room 8 and 9"
      workshops:
          workshop1:
              enabled: true
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room: Meeting Room 10
          workshop2:
              enabled: true
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room: Meeting Room 10
          workshop3:
              enabled: true
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room: Meeting Room 10
