events:
  - virtual: false
    show: true
    showAgenda: true
    location: "Cape Town"
    menuTitle: "Cape Town"
    date: "23 May 2023"
    info: "/capetown"
    infoOn: true
    sessionizeId: "3hwiocdj"
    logo: devconfcpt.png
    minattendees: 500
    venue: "Cape Town International Convention Centre 2"
    website: "https://www.cticc.co.za/"
    mapLink: "https://g.page/CTICC2?share"
    lat: "-33.91743373623432"
    long: "18.429546394164426"
    sponsorOpen: true
    colour: blue
    tickets:
      onsale: true
      purchaseSite: "https://www.quicket.co.za/events/202726-devconf-2023-cape-town"
      fullprice:
        price: 2999
        sold_out: false
      earlybird:
        price: 2699  
        sold_out: true  
    rooms: 
      room_1: "Hall 5"
      room_2: "Watsonia"
      room_3: "Bluebell"
      room_4: "Daisy + Freesia + Orchid"
      room_5: "Nerina + Protea" 
    workshops:
      workshop1:
        announceSponsor: false
        sponsor: 
        sponsorLink: 
        title: Morning Workshop
        content: To be announced
        room: Workshop Space in Expo
      workshop2:
        announceSponsor: true
        sponsor: Equal Experts
        sponsorLink: https://www.equalexperts.com/
        title: Afternoon Workshop
        content: To be announced
        room: Workshop Space in Expo
  - virtual: false
    show: true
    showAgenda: true
    location: "Pretoria"
    menuTitle: "Pretoria"
    date: "25 May 2023"
    info: "/pretoria"
    infoOn: true
    sessionizeId: "3hwiocdj"
    logo: devconfpta.png
    minattendees: 500
    venue: "CSIR International Conference Centre"
    website: "https://www.csiricc.co.za/"
    mapLink: "https://goo.gl/maps/DFndScsarXYkhMLJ7"
    lat: "-25.752775506234492"
    long: "28.27698733915744"
    sponsorOpen: true
    colour: pink
    tickets:
      onsale: true
      purchaseSite: "https://www.quicket.co.za/events/201818-devconf-2023-pretoria"
      fullprice:
        price: 2999
        sold_out: false
      earlybird:
        price: 2699  
        sold_out: true     
    rooms: 
      room_1: "Diamond"
      room_2: "Amber"
      room_3: "Amethyst"
      room_4: "Ruby"
      room_5: "Emerald" 
    workshops:
      workshop1:
        announceSponsor: true
        sponsor: cloudandthings.io 
        sponsorLink: https://cloudandthings.io
        title: Morning Workshop
        content: To be announced
        room: Workshop Space
      workshop2:
        announceSponsor: true
        sponsor: Runninghill Software Development (Pty)Ltd 
        sponsorLink: https://www.runninghill.co.za 
        title: Afternoon Workshop
        content: To be announced
        room: Workshop Space