events:
  - virtual: false
    show: true
    location: "Cape Town"
    menuTitle: "Cape Town"
    date: "23 May 2023"
    info: "/capetown"
    infoOn: false
    sessionizeId: ""
    logo: devconfcpt.png
    minattendees: 500
    venue: "Cape Town International Convention Centre 2"
    website: "https://www.cticc.co.za/"
    mapLink: "https://g.page/CTICC2?share"
    lat: "-33.91743373623432"
    long: "18.429546394164426"
    sponsorOpen: false
    colour: blue
    tickets:
      onsale: false
      purchaseSite: "https://www.quicket.co.za/events/150961-devconf-2022-cape-town"
      fullprice:
        price: "R3,142"
        sold_out: true
      earlybird:
        price: "R2,825" 
        sold_out: true  
    rooms: 
      room_1: "Room 1"
      room_2: "Room 2"
      room_3: "Room 3"
      room_4: "Room 4"
      room_5: "Room 5" 
  - virtual: false
    show: true
    location: "Johannesburg"
    menuTitle: "Joburg"
    date: "25 May 2023"
    info: "/joburg"
    infoOn: false
    sessionizeId: ""
    logo: devconfjhb.png
    minattendees: 500
    venue: "CSIR International Conference Centre"
    website: "https://www.csiricc.co.za/"
    mapLink: "https://goo.gl/maps/DFndScsarXYkhMLJ7"
    lat: "-25.752775506234492"
    long: "28.27698733915744"
    sponsorOpen: false
    colour: pink
    tickets:
      onsale: false
      purchaseSite: "https://www.quicket.co.za/events/150895-devconf-2022-johannesburg"
      fullprice:
        price: "R3,142"
        sold_out: true
      earlybird:
        price: "R2,825"  
        sold_out: true     
    rooms: 
      room_1: "Room 1"
      room_2: "Room 2"
      room_3: "Room 3"
      room_4: "Room 4"
      room_5: "Room 5" 