events:
  - location: "Cape Town"
    date: "31 March 2020"
    info: "/capetown"
    sessionizeId: "b5u8ycnc"
    sessionizeDate: "2020-03-31"
    venue: "Century City Conference Centre"
    website: "https://ccconferencecentre.co.za/"
    mapLink: "https://goo.gl/maps/qccHEpfpQbAQ2caD7"
  - location: "Johannesburg"
    date: "2 April 2020"
    info: "/johannesburg"
    sessionizeId: "b5u8ycnc"
    sessionizeDate: "2020-03-31"
    venue: "Gallagher Convention Centre"
    website: "https://gallagher.co.za"
    mapLink: "https://goo.gl/maps/NwCiffFc5eCAtyLr7"