events:
  - virtual: false
    show: true
    showAgenda: true
    location: "Cape Town"
    menuTitle: "Cape Town"
    date: "23 May 2023"
    info: "/capetown"
    infoOn: true
    sessionizeId: "3hwiocdj"
    logo: devconfcpt.png
    minattendees: 500
    venue: "Cape Town International Convention Centre 2"
    website: "https://www.cticc.co.za/"
    mapLink: "https://g.page/CTICC2?share"
    lat: "-33.91743373623432"
    long: "18.429546394164426"
    sponsorOpen: true
    colour: blue
    tickets:
      onsale: true
      totally_sold_out: true
      has_shuttle: false
      has_waiting_list: false
      waiting_list: "https://forms.office.com/r/qVxjgmV94r"
      purchaseSite: "https://www.quicket.co.za/events/202726-devconf-2023-cape-town"
      merch_link: 
      fullprice:
        price: 2999
        sold_out: false
      earlybird:
        price: 2699  
        sold_out: true  
    rooms: 
      room_1: "Hall 5"
      room_2: "Daisy + Freesia + Orchid"
      room_3: "Nerine + Protea"
      room_4: "Watsonia"
      room_5: "Bluebell" 
    workshops:
      workshop1:
        enabled: false
        announceSponsor: false
        sponsor: 
        sponsorLink: 
        title: Morning Workshop
        content1: To be announced
        content2: To be announced
        room: Workshop Space in Expo
      workshop2:
        enabled: true
        announceSponsor: true
        sponsor: Equal Experts
        sponsorLink: https://www.equalexperts.com/
        title: "Equal Experts Data Workshop with Austin Poulton &amp; team"
        content1: "We will be exploring the world of data engineering.<br/>
<strong>Please bring along your laptops for an exciting experience.</strong>"
        content2: "We will be exploring the world of data engineering.<br/>
<strong>Please bring along your laptops for an exciting experience.</strong>"
        room: Workshop Space in Expo
  - virtual: false
    show: true
    showAgenda: true
    location: "Pretoria"
    menuTitle: "Pretoria"
    date: "25 May 2023"
    info: "/pretoria"
    infoOn: true
    sessionizeId: "3hwiocdj"
    logo: devconfpta.png
    minattendees: 500
    venue: "CSIR International Conference Centre"
    website: "https://www.csiricc.co.za/"
    mapLink: "https://goo.gl/maps/DFndScsarXYkhMLJ7"
    lat: "-25.752775506234492"
    long: "28.27698733915744"
    sponsorOpen: true
    colour: pink
    tickets:
      totally_sold_out: true
      onsale: true
      has_shuttle: true
      has_waiting_list: false
      waiting_list: https://forms.office.com/r/KZXA0XQXrf
      purchaseSite: "https://www.quicket.co.za/events/201818-devconf-2023-pretoria"
      merch_link: "https://www.quicket.co.za/events/201818-devconf-2023-pretoria/?preview=t#/merchandise"
      fullprice:
        price: 2999
        sold_out: false
      earlybird:
        price: 2699  
        sold_out: true     
    rooms: 
      room_1: "Diamond Auditorium"
      room_2: "Amber"
      room_3: "Amethyst"
      room_4: "Ruby Auditorium"
      room_5: "Emerald Auditorium" 
    workshops:
      workshop1:
        enabled: true
        announceSponsor: true
        sponsor: cloudandthings.io 
        sponsorLink: https://cloudandthings.io
        title: "Deploying a Serverless ChatGPT Bot with Devan Barwood"
        content1: "This workshop will introduce you to a basic software lifecycle. From infrastructure to application deployment and unit testing.<br/> 

A quick start to learning some of the best practices when deploying an application to AWS.<br/> 

Technologies: Terraform, Github Actions, AWS Serverless Services, Python.<br/>

<strong>Attendees need to bring their own laptops</strong>."
        content2: "This workshop will introduce you to a basic software lifecycle. From infrastructure to application deployment and unit testing.<br/> 

A quick start to learning some of the best practices when deploying an application to AWS.<br/> 

Technologies: Terraform, Github Actions, AWS Serverless Services, Python.<br/>

<strong>Attendees need to bring their own laptops</strong>."
        room: Workshop Space
      workshop2:
        enabled: true
        announceSponsor: true
        sponsor: Runninghill Software Development (Pty)Ltd 
        sponsorLink: https://www.runninghill.co.za 
        title: "Game changing AI tools for full stack apps: Unleash your potential!"
        content1: "<strong>Introduction</strong><br/>Explanation of workshop goals and objectives.<br/>
Overview of the benefits of using AI tools in full stack app development.<br/><br/>
<strong>All attendees to please bring their laptops!</strong>"
        content2: "<strong>Understanding AI Tools for Full Stack App Development</strong><br/>
Explanation of what AI tools are and how they can be used in full stack app development.<br/>
Overview of the different types of AI tools available for full stack app development.<br/>
<br/><strong>Hands-On Session: Using AI Tools in Full Stack App Development</strong><br/>
Participants will work on a guided exercise to use AI tools for full stack app development.<br/>
Participants will learn how to use AI tools to improve their development process.<br/>
<br/><strong>Best Practices for Using AI Tools in Full Stack App Development</strong><br/>
Overview of best practices for using AI tools in full stack app development.<br/>
Discussion of how AI tools can improve productivity and creativity in full stack app development.<br/>
<br/><strong>Conclusion</strong><br/>
Recap of workshop topics and discussion of next steps.<br/>
Q&A session with workshop participants."
        room: Workshop Space