sponsors:
    proposal: /public/docs/DevConf 2024 Sponsorship Proposal.pdf
callForSpeakers:
    show: false
    link: https://sessionize.com/devconf-2024
events:
    - virtual: false
      show: true
      showAgenda: true
      location: "Johannesburg"
      menuTitle: "Joburg"
      date: "7 May 2024"
      info: "/joburg"
      infoOn: true
      sessionizeId: "b0tah92u"
      logo: devconfjhb.png
      minattendees: 700
      venue: "Emperors Palace Conference Centre"
      website: "https://emperorspalace.com/conferences-overview/"
      mapLink: "https://goo.gl/maps/eQKGw5XmjA5RjPQa8"
      lat: "-26.146498178859964"
      long: "28.223241542328243"
      sponsorOpen: true
      colour: pink
      tickets:
          totally_sold_out: false
          onsale: true
          has_shuttle: false
          has_waiting_list: false
          waiting_list:
          purchaseSite: "https://www.quicket.co.za/events/237752-devconf-2024-johannesburg"
          merch_link: ""
          fullprice:
              price: 3623
              bulkPrice: 3293.64
              sold_out: false
          earlybird:
              price: 3150.43
              sold_out: true
      rooms:
          room_1: "Centre Court"
          room_2: "NCC"
          room_3: "Senate I"
          room_4: "Senate II"
          room_5: "Fabia"
      workshops:
          workshop1:
              enabled: true
              announceSponsor: true
              sponsor: iOCO
              sponsorLink: https://ioco.tech/  
              title: "From Complexity to Clarity: Navigating Microservices with Kubernetes"
              content1: "In today&#39;s dynamic software development landscape, adopting microservices is key to
achieving greater scalability, flexibility, and faster innovation. While the benefits of
microservices are clear, they come with their own set of complexities. Successfully
implementing a microservices architecture extends beyond breaking down
applications; it demands a thorough understanding of deployment, management, and
observability. The prevalent adoption of the &quot;You Build It, You Run It&quot; philosophy
marks a significant shift towards developer accountability and empowerment. As a
modern developer understanding the platform your applications run on, is not just
beneficial, it&#39;s essential.<br/>
We invite you to a technical session tailored for forward-thinking developers ready to
tackle the challenges of deploying microservices using Kubernetes. This session is
focused on demystifying the deployment platforms that will house your applications,
emphasizing the early adoption of practices such as logging, tracing, monitoring to
name a few.<br/>
The session will cover:<ul>
<li>Preparing Your Development Environment</li>
<li>Crafting Docker Images</li>
<li>Application Deployment with Kubernetes</li>
<li>Monitoring and Troubleshooting Techniques within Kubernetes</li>
<li>Security Measures and Best Practices</li>
<li>Exploring Advanced Features of Kubernetes</li></ul>"
              content2:
              room: Julia
          workshop2:
              enabled: true
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              room: Julia
          workshop3:
              enabled: true
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              room: Julia
    - virtual: false
      show: true
      showAgenda: true
      location: "Cape Town"
      menuTitle: "Cape Town"
      date: "9 May 2024"
      info: "/capetown"
      infoOn: true
      sessionizeId: "b0tah92u"
      logo: devconfcpt.png
      minattendees: 700
      venue: "Century City Conference Centre"
      website: "http://ccconferencecentre.co.za/"
      mapLink: "https://goo.gl/maps/T8F9LTbNdFHZTEzw9"
      lat: "-33.895519679277136"
      long: "18.504693653133835"
      sponsorOpen: true
      colour: blue
      tickets:
          onsale: true
          totally_sold_out: false
          has_shuttle: false
          has_waiting_list: false
          waiting_list: ""
          purchaseSite: "https://www.quicket.co.za/events/239304-devconf-2024-cape-town"
          merch_link:
          fullprice:
              price: 3623
              sold_out: false
              bulkPrice: 3293.64
          earlybird:
              price: 3150.43
              sold_out: true
      rooms:
          room_1: "Hall A"
          room_2: "Hall B"
          room_3: "Hall C"
          room_4: "Meeting Room 11"
          room_5: "Meeting Room 8 and 9"
      workshops:
          workshop1:
              enabled: true
              announceSponsor: true
              sponsor: iOCO
              sponsorLink: https://ioco.tech/  
              title: "From Complexity to Clarity: Navigating Microservices with Kubernetes"
              content1: "In today&#39;s dynamic software development landscape, adopting microservices is key to
achieving greater scalability, flexibility, and faster innovation. While the benefits of
microservices are clear, they come with their own set of complexities. Successfully
implementing a microservices architecture extends beyond breaking down
applications; it demands a thorough understanding of deployment, management, and
observability. The prevalent adoption of the &quot;You Build It, You Run It&quot; philosophy
marks a significant shift towards developer accountability and empowerment. As a
modern developer understanding the platform your applications run on, is not just
beneficial, it&#39;s essential.<br/>
We invite you to a technical session tailored for forward-thinking developers ready to
tackle the challenges of deploying microservices using Kubernetes. This session is
focused on demystifying the deployment platforms that will house your applications,
emphasizing the early adoption of practices such as logging, tracing, monitoring to
name a few.<br/>
The session will cover:<ul>
<li>Preparing Your Development Environment</li>
<li>Crafting Docker Images</li>
<li>Application Deployment with Kubernetes</li>
<li>Monitoring and Troubleshooting Techniques within Kubernetes</li>
<li>Security Measures and Best Practices</li>
<li>Exploring Advanced Features of Kubernetes</li></ul>"
              content2:
              room: Meeting Room 10
          workshop2:
              enabled: true
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room: Meeting Room 10
          workshop3:
              enabled: true
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room: Meeting Room 10
