events:
  - location: "Cape Town"
    menuTitle: "Cape Town"
    date: "31 March 2020"
    info: "/capetown"
    sessionizeId: "b5u8ycnc"
    logo: devconfcpt.png
    # sessionizeId: "f0el0uow"
    venue: "Century City Conference Centre"
    website: "https://ccconferencecentre.co.za/"
    mapLink: "https://goo.gl/maps/qccHEpfpQbAQ2caD7"
    lat: "-33.895791"
    long: "18.50296"
    tickets:
      purchaseSite: https://www.quicket.co.za/events/82483-devconf-2020-cape-town-
      earlyBird:
        price: R1,880.00
        sold_out: true
      solo:
        price: R1,997.50
      corporate:
        price: R2,350.00     
  - location: "Johannesburg"
    menuTitle: "Joburg"
    date: "2 April 2020"
    info: "/johannesburg"
    sessionizeId: "b5u8ycnc"
    logo: devconfjhb.png
    # sessionizeId: "f0el0uow"
    venue: "Gallagher Convention Centre"
    website: "https://gallagher.co.za"
    mapLink: "https://goo.gl/maps/NwCiffFc5eCAtyLr7"
    lat: "-26.0014965"
    long: "28.1273613"
    tickets:
      purchaseSite: https://www.quicket.co.za/events/86889-devconf-2020-johannesburg
      earlyBird:
        price: R2,092.00
      solo:
        price: R2,222.75
      corporate:
        price: R2,615.00        