general:
    year: "2026"

banner:
    show: false
    content: "DevConf 2026 is entirely sold out! We can't wait to see you all soon!"

mailingList:
    show: true

sponsors:
    show: true
    proposal: /sponsorship
    banner: true

callForSpeakers:
    prep: false
    openDate: "1 November 2025"
    show: false
    link: https://sessionize.com/devconf-2026/

ratings:
    open: false

events:
    - virtual: false
      show: true
      showAgenda: true
      location: "Johannesburg"
      menuTitle: "Joburg"
      date: "12 May 2026"
      info: "/joburg"
      infoOn: true
      sessionizeId: "6x7s5svg"
      logo: devconfjhb.png
      minattendees: 500
      venue: "The Canvas @ Riversands"
      website: "https://www.thecanvasriversands.co.za/"
      mapLink: "https://maps.app.goo.gl/R6cmNWZtpxVbAM477"
      lat: "-25.963033894554854"
      long: "28.02281384929991"
      sponsorOpen: true
      colour: pink
      tickets:
          totally_sold_out: false
          onsale: true
          has_shuttle: false
          has_waiting_list: false
          waiting_list:
          purchaseSite: "https://www.quicket.co.za/events/338615-devconf-2026-johannesburg/"
          merch_link: ""
          fullprice:
              price: 4255.00
              bulkPrice: 3829.50
              sold_out: false
          earlybird:
              price: 3616.75
              sold_out: false
      rooms:
          room_1: "Centre Court"
          room_2: "NCC"
          room_3: "Senate I"
          room_4: "Senate II"
          room_5: "Fabia"
      timing:
          reg-start: 07h30
          reg-end: 08h45
          expo-start: 08h00
          expo-end: 19h00
          welcome-start: 08h45
          keynote-start: 09h15
          refresh-1-start: 10h00
          timeslot-1-start: 10h30
          movement-1-start: 11h10
          timeslot-2-start: 11h20
          movement-2-start: 12h00
          timeslot-3-start: 12h10
          lunch-start: 12h50
          timeslot-4-start: 13h40
          movement-3-start: 14h20
          timeslot-5-start: 14h30
          refresh-2-start: 15h10
          timeslot-6-start: 15h25
          movement-4-start: 16h05
          timeslot-7-start: 16h15
          movement-5-start: 16h55
          thank-you-start: 17h05
          networking-start: 17h30
          networking-end: 19h00
      workshops:
          workshop1:
              enabled: false
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room:
          workshop2:
              enabled: false
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room:
          workshop3:
              enabled: false
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room:

    - virtual: false
      show: true
      showAgenda: true
      location: "Cape Town"
      menuTitle: "Cape Town"
      date: "14 May 2026"
      info: "/capetown"
      infoOn: true
      sessionizeId: "6x7s5svg"
      logo: devconfcpt.png
      minattendees: 700
      venue: "Century City Conference Centre"
      website: "http://ccconferencecentre.co.za/"
      mapLink: "https://goo.gl/maps/T8F9LTbNdFHZTEzw9"
      lat: "-33.895519679277136"
      long: "18.504693653133835"
      sponsorOpen: true
      colour: blue
      tickets:
          onsale: true
          totally_sold_out: false
          has_shuttle: false
          has_waiting_list: false
          waiting_list: ""
          purchaseSite: "https://www.quicket.co.za/events/345686-devconf-2026-cape-town/"
          merch_link:
          fullprice:
              price: 4255.00
              bulkPrice: 3829.50
              sold_out: false
          earlybird:
              price: 3616.75
              sold_out: false
      rooms:
          room_1: "Hall A"
          room_2: "Hall B"
          room_3: "Hall C"
          room_4: "The Verve"
          room_5: "Meeting Room 11"
      timing:
          reg-start: 07h30
          reg-end: 08h45
          expo-start: 08h00
          expo-end: 19h00
          welcome-start: 08h45
          keynote-start: 09h00
          refresh-1-start: 9h45
          timeslot-1-start: 10h15
          movement-1-start: 10h55
          timeslot-2-start: 11h05
          movement-2-start: 11h45
          timeslot-3-start: 11h55
          lunch-start: 12h35
          timeslot-4-start: 13h30
          movement-3-start: 14h10
          timeslot-5-start: 14h20
          refresh-2-start: 15h00
          timeslot-6-start: 15h15
          movement-4-start: 15h55
          timeslot-7-start: 16h05
          movement-5-start: 16h45
          thank-you-start: 16h55
          networking-start: 17h15
          networking-end: 19h00
      workshops:
          workshop1:
              enabled: false
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room:
          workshop2:
              enabled: false
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room:
          workshop3:
              enabled: false
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room:
