events:
  - virtual: false
    show: true
    location: "Cape Town"
    menuTitle: "Cape Town"
    date: "23 May 2023"
    info: "/capetown"
    infoOn: true
    sessionizeId: ""
    logo: devconfcpt.png
    minattendees: 500
    venue: "Cape Town International Convention Centre 2"
    website: "https://www.cticc.co.za/"
    mapLink: "https://g.page/CTICC2?share"
    lat: "-33.91743373623432"
    long: "18.429546394164426"
    sponsorOpen: true
    colour: blue
    tickets:
      onsale: true
      purchaseSite: "https://www.quicket.co.za/events/202726-devconf-2023-cape-town"
      fullprice:
        price: 2999
        sold_out: false
      earlybird:
        price: 2699  
        sold_out: true  
    rooms: 
      room_1: "Room 1"
      room_2: "Room 2"
      room_3: "Room 3"
      room_4: "Room 4"
      room_5: "Room 5" 
  - virtual: false
    show: true
    location: "Pretoria"
    menuTitle: "Pretoria"
    date: "25 May 2023"
    info: "/pretoria"
    infoOn: true
    sessionizeId: ""
    logo: devconfpta.png
    minattendees: 500
    venue: "CSIR International Conference Centre"
    website: "https://www.csiricc.co.za/"
    mapLink: "https://goo.gl/maps/DFndScsarXYkhMLJ7"
    lat: "-25.752775506234492"
    long: "28.27698733915744"
    sponsorOpen: true
    colour: pink
    tickets:
      onsale: true
      purchaseSite: "https://www.quicket.co.za/events/201818-devconf-2023-pretoria"
      fullprice:
        price: 2999
        sold_out: false
      earlybird:
        price: 2699  
        sold_out: true     
    rooms: 
      room_1: "Room 1"
      room_2: "Room 2"
      room_3: "Room 3"
      room_4: "Room 4"
      room_5: "Room 5" 