banner:
    show: false
    content: "DevConf 2025 is entirely sold out! We can't wait to see you all soon!"
sponsors:
    show: true
    proposal: /public/docs/DevConf 2025 Sponsorship Proposal.pdf
    banner: true
callForSpeakers:
    show: false
    link: https://sessionize.com/devconf-2025
timing:
    reg-start: 07h30
    reg-end: 08h45
    expo-start: 08h00
    expo-end: 19h00
    welcome-start: 08h45
    keynote-start: 09h00
    refresh-1-start: 9h45
    timeslot-1-start: 10h15
    movement-1-start: 10h55
    timeslot-2-start: 11h05
    movement-2-start: 11h45
    timeslot-3-start: 11h55
    lunch-start: 12h35
    timeslot-4-start: 13h30
    movement-3-start: 14h10
    timeslot-5-start: 14h20
    refresh-2-start: 15h00
    timeslot-6-start: 15h15
    movement-4-start: 15h55
    timeslot-7-start: 16h05
    movement-5-start: 16h45
    thank-you-start: 16h55
    networking-start: 17h15
    networking-end: 19h00

general:
    year: "2025"
events:
    - virtual: false
      show: true
      showAgenda: true
      location: "Johannesburg"
      menuTitle: "Joburg"
      date: "27 May 2025"
      info: "/joburg"
      infoOn: true
      sessionizeId: "fs0wbo5v"
      logo: devconfjhb.png
      minattendees: 700
      venue: "Emperors Palace Conference Centre"
      website: "https://emperorspalace.com/conferences-overview/"
      mapLink: "https://goo.gl/maps/eQKGw5XmjA5RjPQa8"
      lat: "-26.146498178859964"
      long: "28.223241542328243"
      sponsorOpen: true
      colour: pink
      tickets:
          totally_sold_out: false
          onsale: true
          has_shuttle: false
          has_waiting_list: false
          waiting_list:
          purchaseSite: "https://www.quicket.co.za/events/286990-devconf-2025-johannesburg/#/"
          merch_link: ""
          fullprice:
              price: 3985.29
              bulkPrice: 3622.99
              sold_out: false
          earlybird:
              price: 3465.47
              sold_out: true
      rooms:
          room_1: "Centre Court"
          room_2: "NCC"
          room_3: "Senate I"
          room_4: "Senate II"
          room_5: "Fabia"
      workshops:
          workshop1:
              enabled: false
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room:
          workshop2:
              enabled: false
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room:
          workshop3:
              enabled: false
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room:

    - virtual: false
      show: true
      showAgenda: true
      location: "Cape Town"
      menuTitle: "Cape Town"
      date: "29 May 2025"
      info: "/capetown"
      infoOn: true
      sessionizeId: "fs0wbo5v"
      logo: devconfcpt.png
      minattendees: 700
      venue: "Century City Conference Centre"
      website: "http://ccconferencecentre.co.za/"
      mapLink: "https://goo.gl/maps/T8F9LTbNdFHZTEzw9"
      lat: "-33.895519679277136"
      long: "18.504693653133835"
      sponsorOpen: true
      colour: blue
      tickets:
          onsale: true
          totally_sold_out: false
          has_shuttle: false
          has_waiting_list: false
          waiting_list: ""
          purchaseSite: "https://www.quicket.co.za/events/285080-devconf-2025-cape-town/#/"
          merch_link:
          fullprice:
              price: 3985.29
              bulkPrice: 3622.99
              sold_out: false
          earlybird:
              price: 3465.47
              sold_out: true
      rooms:
          room_1: "Hall A"
          room_2: "Hall B"
          room_3: "Hall C"
          room_4: "The Verve"
          room_5: "Meeting Room 11"
      workshops:
          workshop1:
              enabled: false
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room:
          workshop2:
              enabled: false
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room:
          workshop3:
              enabled: false
              announceSponsor: false
              sponsor:
              sponsorLink:
              title:
              content1:
              content2:
              room:
